onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /bench/main_inst/spi_slaver_inst/clk
add wave -noupdate /bench/main_inst/spi_slaver_inst/rstn
add wave -noupdate /bench/main_inst/spi_slaver_inst/cs
add wave -noupdate /bench/main_inst/spi_slaver_inst/sck
add wave -noupdate /bench/main_inst/spi_slaver_inst/MOSI
add wave -noupdate /bench/main_inst/spi_slaver_inst/MISO
add wave -noupdate /bench/main_inst/spi_slaver_inst/rxd_out
add wave -noupdate /bench/main_inst/spi_slaver_inst/txd_data
add wave -noupdate /bench/main_inst/spi_slaver_inst/rxd_flag
add wave -noupdate /bench/main_inst/spi_slaver_inst/rxd_data
add wave -noupdate /bench/main_inst/spi_slaver_inst/sck_r0
add wave -noupdate /bench/main_inst/spi_slaver_inst/sck_r1
add wave -noupdate /bench/main_inst/spi_slaver_inst/sck_n
add wave -noupdate /bench/main_inst/spi_slaver_inst/sck_p
add wave -noupdate /bench/main_inst/spi_slaver_inst/rxd_flag_r
add wave -noupdate /bench/main_inst/spi_slaver_inst/rxd_state
add wave -noupdate /bench/main_inst/spi_slaver_inst/rxd_flag_r0
add wave -noupdate /bench/main_inst/spi_slaver_inst/rxd_flag_r1
add wave -noupdate /bench/main_inst/spi_slaver_inst/txd_state
add wave -noupdate /bench/main_inst/dac_inst/resetn
add wave -noupdate /bench/main_inst/dac_inst/clk
add wave -noupdate /bench/main_inst/dac_inst/dac_clk
add wave -noupdate /bench/main_inst/dac_inst/dac_data
add wave -noupdate /bench/main_inst/dac_inst/rxd_out
add wave -noupdate /bench/main_inst/dac_inst/rxd_flag
add wave -noupdate /bench/main_inst/dac_inst/buffer_wr_dv
add wave -noupdate /bench/main_inst/dac_inst/buffer_wr_addr
add wave -noupdate /bench/main_inst/dac_inst/buffer_wr_data
add wave -noupdate /bench/main_inst/dac_inst/buffer_rd_dv
add wave -noupdate /bench/main_inst/dac_inst/buffer_rd_addr
add wave -noupdate /bench/main_inst/dac_inst/oag_output_ctrl
add wave -noupdate /bench/main_inst/dac_inst/oag_init_ctrl
add wave -noupdate /bench/main_inst/dac_inst/recv_data_ct
add wave -noupdate /bench/main_inst/dac_inst/state
add wave -noupdate /bench/main_inst/dac_inst/state_next
add wave -noupdate /bench/main_inst/adc_inst/resetn
add wave -noupdate /bench/main_inst/adc_inst/clk
add wave -noupdate /bench/main_inst/adc_inst/adc_clk
add wave -noupdate /bench/main_inst/adc_inst/adc_data
add wave -noupdate /bench/main_inst/adc_inst/txd_data
add wave -noupdate /bench/main_inst/adc_inst/rxd_flag
add wave -noupdate /bench/main_inst/adc_inst/fifo_wr_dv
add wave -noupdate /bench/main_inst/adc_inst/fifo_full
add wave -noupdate /bench/main_inst/adc_inst/fifo_empty
add wave -noupdate /bench/main_inst/adc_inst/fifo_rd_dv
add wave -noupdate /bench/main_inst/adc_inst/fifo_rd_data
add wave -noupdate /bench/main_inst/adc_inst/fifo_data_rnum
add wave -noupdate /bench/main_inst/adc_inst/state
add wave -noupdate /bench/main_inst/adc_inst/state_next
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {151104100 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 319
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {150781147 ps} {151767546 ps}
