-d D:\Tasks\PocketLab-RTL\impl\gwsynthesis\PocketLab-RTL.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst D:\Tasks\PocketLab-RTL\src\main.cst
-cfg D:\Tasks\PocketLab-RTL\impl\pnr\device.cfg
-sdc D:\Tasks\PocketLab-RTL\src\main.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
